### ISSUE TITLE
License file

### ISSUE THREAD

**Issue by gwpl** [uzuzjmd/Wissensmodellierung#25]
Hi!

I've found this repo on graphdracula.net,
however after skimming I didn't notice LICENSE file with some permissive license (like dracula on MIT).

Could you please add license file?

Thanks,
Greg

**Comment by uzuzjmd** [comment]
Hi,

I included the licensing in the html file but it must have dropped in some version. Can you send me a file that fits the purpose as I am not sure how it is supposed to look like?

We are refactoring the project to use primefaces graphs so the dracula lib will probably not be relevant in any release. By the way, good job on the framework.

Yours,
Julian

**Comment by uzuzjmd** [comment]
I habe committed license.txt which refers to the dracula website for license questions regarding the dracula framework. If you want me to delete the framework from the repo, comment this issue. So far closing this issue.

**Comment by gwpl** [comment]
Hi!

Thank you for addressing issue.
Below are exmaples how repositories with autogenerated LICENSE files look like.
In order to try it for another license, just create new Github repository with autogenerate LICENSE file and then merge it/copy it into your repository. This will be for sure the safest way to make sure it not only human, but also machine readable :).

* https://github.com/gwpl/test_autogen_MIT_LICENSE
* https://github.com/gwpl/test_autogen_Apache2.0_LICENSE

Good luck with project!
Grzegorz Wierzowiecki
